#!/usr/bin/env bash
# Cadencia setup wizard.
# Writes .env and, if a custom DB path is chosen, docker-compose.override.yml.
# Run via: make bootstrap
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

B='\033[1m'
C='\033[0;36m'
G='\033[0;32m'
Y='\033[0;33m'
R='\033[0;31m'
N='\033[0m'

ask() {
    local prompt="$1" default="$2" var="$3"
    printf "${C}%s${N} [${B}%s${N}]: " "$prompt" "$default"
    read -r _ans
    printf -v "$var" '%s' "${_ans:-$default}"
}

ask_yn() {
    local prompt="$1" default="$2" var="$3"
    printf "${C}%s${N} [${B}%s${N}]: " "$prompt" "$default"
    read -r _ans
    _ans="${_ans:-$default}"
    [[ "$_ans" =~ ^[Yy] ]] && printf -v "$var" 'y' || printf -v "$var" 'n'
}

section() { printf "\n${B}--- %s ---${N}\n" "$1"; }

# -----------------------------------------------------------------------

printf "\n${B}Cadencia setup${N}\n"
printf "Writes .env (and docker-compose.override.yml if needed).\n"

if [[ -f "$REPO_ROOT/.env" ]]; then
    printf "\n${Y}.env already exists.${N}\n"
    ask_yn "Overwrite it?" "n" overwrite
    [[ "$overwrite" == "y" ]] || { echo "Aborted. Existing .env kept."; exit 0; }
fi

# --- Database -----------------------------------------------------------
section "Database"
printf "By default the database lives in a Docker named volume (cadencia_data).\n"
printf "You can instead mount a host directory so the file is directly accessible.\n\n"

ask_yn "Use a host directory for the database?" "n" use_bind

DATA_DIR=""
if [[ "$use_bind" == "y" ]]; then
    ask "Host path for database directory" "$HOME/.local/share/cadencia" DATA_DIR
    DATA_DIR="${DATA_DIR/#\~/$HOME}"
    mkdir -p "$DATA_DIR"
    printf "${G}Directory ready: %s${N}\n" "$DATA_DIR"
fi

# --- Backup -------------------------------------------------------------
section "Backup (Google Drive via rclone)"
ask "rclone remote name" "gdrive" RCLONE_REMOTE
ask "Folder name on Google Drive" "cadencia-backups" BACKUP_PATH
ask "Backup hour in UTC (0-23)" "3" BACKUP_HOUR

# --- Staleness thresholds -----------------------------------------------
section "Staleness thresholds"
ask "Days before an allocation is flagged stale" "45" ALLOC_STALE
ask "Days before a 1:1 is flagged overdue" "14" OO_STALE

# --- Ports --------------------------------------------------------------
section "Ports"
ask "Web UI port" "8080" APP_PORT
ask "MCP server port" "8081" MCP_PORT

# --- Write .env ---------------------------------------------------------
cat > "$REPO_ROOT/.env" <<EOF
# Generated by make bootstrap on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit directly or re-run make bootstrap to regenerate.

# Logical owner ID (leave as "default" for single-user installs)
OWNER_ID=default

# Backup
RCLONE_REMOTE=${RCLONE_REMOTE}
BACKUP_PATH=${BACKUP_PATH}
BACKUP_HOUR=${BACKUP_HOUR}

# Staleness thresholds (days)
ALLOCATION_STALE_DAYS=${ALLOC_STALE}
ONE_ON_ONE_STALE_DAYS=${OO_STALE}

# Ports
APP_PORT=${APP_PORT}
MCP_PORT=${MCP_PORT}

# Log level: DEBUG, INFO, WARNING, ERROR
LOG_LEVEL=INFO
EOF

printf "\n${G}.env written.${N}\n"

# --- Write override if bind mount requested -----------------------------
OVERRIDE="$REPO_ROOT/docker-compose.override.yml"

if [[ -n "$DATA_DIR" ]]; then
    cat > "$OVERRIDE" <<EOF
# Auto-generated by make bootstrap on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Delete this file to revert to the default Docker named volume.
services:
  app:
    volumes:
      - ${DATA_DIR}:/data
      - backup_status:/backup-status:ro
  mcp:
    volumes:
      - ${DATA_DIR}:/data
  backup:
    volumes:
      - ${DATA_DIR}:/data:ro
      - backup_status:/backup-status
      - ./secrets:/secrets:ro
EOF
    printf "${G}docker-compose.override.yml written.${N}\n"
    printf "Database will be stored at: ${B}%s/em.db${N}\n" "$DATA_DIR"
else
    # Remove a stale override if the user switched back to the named volume
    if [[ -f "$OVERRIDE" ]]; then
        rm "$OVERRIDE"
        printf "Removed existing docker-compose.override.yml (using named volume).\n"
    fi
    printf "Database will be stored in Docker volume: ${B}cadencia_data${N}\n"
fi

printf "\n${G}Done.${N} Run ${B}make up${N} to start.\n\n"
